name: Update ECS Task Workflows

on:
  workflow_dispatch:
 # push:
  #  branches:
   #   - main

jobs:
  update-ecs-task:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}

    steps:
      - name: Checkout the script repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub requests

      - name: Run the update script
        run: python script.py
